### ISSUE TITLE
rxjs operators are incorrectly imported into the project and can't be compiled

### ISSUE THREAD

**Issue by JaroslavX** [angular-redux2/store#13]
Hello, Could you please update the imports from rxjs library? 

* [ ] feature request
* [+ ] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [+ ] @angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version:
Typescript Version:
Angular Version:
@angular-redux/store version:
@angular/cli version: (if applicable)
OS:

### Link to repo showing the issue
(optional, but helps _a lot_)

### Expected Behaviour:
Correct imports from the library

### Actual Behaviour:
Incorrect paths are used for rxjs library

### Stack Trace/Error Message:

hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:364:53-56 - Error: export 'map' (imported as 'map') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:364:78-98 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:546:31-51 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:546:55-58 - Error: export 'map' (imported as 'map') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:546:80-100 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:1238:98-118 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
✔ Browser application bundle generation complete.
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:364:53-56 - Error: export 'map' (imported as 'map') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:364:78-98 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:546:31-51 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:546:55-58 - Error: export 'map' (imported as 'map') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:546:80-100 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | ./node_modules/@angular-redux2/store/fesm2015/angular-redux2-store.mjs:1238:98-118 - Error: export 'distinctUntilChanged' (imported as 'distinctUntilChanged') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 
hero3-main-hero_setup_runner-1  | hero_frontend_1  | 

### Additional Notes:
(optional)

**Comment by JaroslavX** [comment]
The main problem is in this file
![image](https://user-images.githubusercontent.com/1561909/205704161-36fd9b4f-3779-41e5-a2ce-296e45dfff9a.png)
It should be changed to:
![image](https://user-images.githubusercontent.com/1561909/205704314-a6982b81-7f56-4fc1-8184-c8ab0f7f0130.png)

**Comment by Garefild** [comment]
which version of angular and rxjs are you using?

**Comment by JaroslavX** [comment]
@angular/core": "12.2.17
"rxjs": "6.5.5",

**Comment by JaroslavX** [comment]
The issue was caused by an outdated version of rxjs library. The best approach will be to update it to version "rxjs": "~7.5.0" in my project. It would be great to add a warning during the npm installation step to notify about that incompatibility.

**Comment by Garefild** [comment]
I will add a warning during the npm install phase to notify you of this incompatibility.
Thanks!
